### ISSUE TITLE
When the date changes, although the current cache is comitted within a few seconds, it has the wrong day's timestamp

### ISSUE THREAD

**Issue by joocer** [gva-jjoyce/gva_data#10]
The feature which closes off an open streaming dataset when the day changes does close off the partition, but the code which commits the partition uses the current date, i.e. the day after the data in the partition.

**Comment by gva-jjoyce** [comment]
Version 0.2 moves the responsibility for naming the partition to the point of when the data is written, this means that when the clock does change, the name of the partition will be actioned immediately.

**Comment by gva-jjoyce** [comment]
Code to determine the name of the partition has been completely rewritten and this problem has been designed out.
