### ISSUE TITLE
Create an optimized text search

### ISSUE THREAD

**Issue by joocer** [gva-jjoyce/gva_data#12]
Most searches will be for strings, search for this username, search for that server, search for that status. There should be a variation of the search which is optimized for text searches. The text search would be blunt, perhaps mismatching on the field and data labels as well as the data content.

If the files are quickly filtered, the reduced records are then parsed before the WHERE or SELECT statements applied, on some searches some files will not need to be iterated over each record in a file.

**Comment by joocer** [comment]
It takes approximately 1/200th second to determine if a substring is in a 16Mb block of text. Using this to determine if a file should be iterated over - the impact on files which are read is minimal (additional 1/200th second) - if the file isn't read, it could save 1/16th second just to read - the final impact would be larger as the records wouldn't be JSON parsed.

Fastest search found so far is:
~~~
instances = [m.start() for m in re.finditer(search, corpus)]
~~~
note this is much faster than `search in corpus` - there are likely to be even faster searches as the above code finds all instances of the substring when it only needs to find one instance to fulfil this purpose.

**Comment by gva-jjoyce** [comment]
migrated to org
