### ISSUE TITLE
Requiring paths to contain %datefolders and to end in '/' makes it too easy for users to make mistakes

### ISSUE THREAD

**Issue by gva-jjoyce** [gva-jjoyce/gva_data#3]
Without %datefolders (or equivalent) on Reader paths, the Reader will default to returning the data from every day, this is rarely the desired behaviour. The Reader should assume the current day (or latest, see Issue #2) when no date is provided.

Not automatically recognising paths as paths when the user has not ended the path with a '/' may result in unexpected or unwanted behaviour - if the user has entered a path, even without a concluding '/', the Reader should recognise as a path and act as if it concludes with a '/'

**Comment by joocer** [comment]
'/' added, all regression tests pass

**Comment by gva-jjoyce** [comment]
migrated to org
