### ISSUE TITLE
Library choice makes it difficult to use cross-platform

### ISSUE THREAD

**Issue by gva-jjoyce** [gva-jjoyce/gva_data#7]
The orjson librarymis not trivial to install on some platforms, such as Raspberry Pis. If available, the code should prefer orjson, otherwise, it should fallback to ujson.

**Comment by joocer** [comment]
ujson and orjson are not compatible - ujson does not serialize dates whereas orjson does, additional work is required to ensure graceful fallback

**Comment by joocer** [comment]
new module added to common which contains logic for falling back to ujson is orjson isn't installed. This module includes some code to compensate for the differences between these two libraries. There is no performance impact to systems with orjson installed, there is some degradation to systems without orjson on the performance of ujson - however this is still more perfomant than using native json.

Tests have been written, although as most of the code only runs during an ImportError, pytest doesn't reach it, attempts to force pytest to cover broke pytest.

A test exists but it is removed from the automated testing.

**Comment by joocer** [comment]
The library is installed and running on a Raspberry Pi.

**Comment by joocer** [comment]
Pipelines and Minio reader/writers all running on Raspberry Pi without issue - at least one operator was using the orjson library directly - these should be addressed as they are found.

**Comment by gva-jjoyce** [comment]
Working on Windows, Raspbian Light, MacOS and GCP AI Notebooks - closing
